name: Website Docs - pull-request workflow
on:
  pull_request:
    paths:
      # And they said my half-pyramid print program is going to be useless
      #
      # This unfortunately is a hack that is actually the "official" way of
      # supporting multiple projects in one repo:
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#example-matching-paths-in-nested-directories
      #
      # This is because the wildcard asterisk '*'' drops the '/' and it is not
      # possible to overcome this by other means.
      #
      # You are welcome to join the rant of this outrageous atrocity:
      # https://github.community/t5/GitHub-Actions/GitHub-Actions-workflow-not-triggered-with-path/m-p/29872    
      - 'websites/docs/*'
      - 'websites/docs/*/*'
      - 'websites/docs/*/*/*'
      - 'websites/docs/*/*/*/*'
      - 'websites/docs/*/*/*/*/*'
      - 'websites/docs/*/*/*/*/*/*'
      - 'websites/docs/*/*/*/*/*/*/*'
      - 'websites/docs/*/*/*/*/*/*/*/*'
      - 'websites/docs/*/*/*/*/*/*/*/*/*'
      - 'websites/docs/*/*/*/*/*/*/*/*/*/*'
      - 'websites/docs/*/*/*/*/*/*/*/*/*/*/*'
      - 'websites/docs/*/*/*/*/*/*/*/*/*/*/*/*'
      - 'websites/docs/*/*/*/*/*/*/*/*/*/*/*/*/*'
      - 'websites/docs/*/*/*/*/*/*/*/*/*/*/*/*/*/*'
      - 'websites/docs/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*'
jobs:
  build:
    name: Netlify deploy preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build docs website
        run: "ls websites/docs"  # TODO - build
      - name: Install Netlify CLI
        run: "sudo npm install netlify-cli -g"
      - name: Netlify deploy
        run: "netlify deploy --auth ${NETLIFY_AUTH_TOKEN} --site ${NETLIFY_SITE_ID} --dir=./websites/docs --json --message \"Deploy preview commit: ${GITHUB_SHA}\" | tee _netlify_deploy_response.txt"
        env:
          NETLIFY_SITE_ID: 02b203ae-f58b-4914-842d-61230f0d64e7
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Comment with the deploy preview url
        uses: actions/github-script@0.2.0
        if: success()
        with:
          github-token: ${{ github.token }}
          script: |
            const require = global.require || global.process.mainModule.constructor._load;
            const fs = require("fs");
            let netlify = await JSON.parse(await fs.readFileSync('_netlify_deploy_response.txt', 'utf-8'));
            await github.issues.createComment({...context.issue, body: `\[Deploy preview](${netlify.deploy_url}) ready.`});
